---
title: "Interactive plots"
author: "Jess"
date: "2022-09-16"
output: html_document
runtime: shiny
---

```{r setup,echo=FALSE, results='hide', warning=FALSE, message=FALSE}
library(tidyverse)
library(ggiraph)
library(ggthemes)
library(cowplot)
```

```{r Load Data, echo=FALSE, results='hide', warning=FALSE}
setwd("~/OneDrive - Louisiana State University/MOSB Lab/Thesis/Analyses")
library(readxl)
EMA_DF <- read_excel("WorkingDataFrame.xlsx", sheet = "ambulatory")
EMA_DFPlot <- subset(EMA_DF, select = c("ID", "ObsNum", "SI", "Hopelessness_Raw", "TB_Raw", "PB_Raw"))

EMA_DF$ID <- as.factor(EMA_DF$ID)

row.has.na <- apply(EMA_DF, 1, function(x){any(is.na(x))})
sum(row.has.na)
EMA_DFPlot <- EMA_DF[!row.has.na,]
```

```{r echo=FALSE, results='hide', warning=FALSE}
TestPlot <- ggplot(EMA_DF, aes(x = ObsNum, y= Hopelessness_Raw)) +
  geom_line(aes(color=ID), size = 0.6) +
  theme_light() +
  xlab("Observation Number") +
  theme(axis.title.y = element_blank(), legend.position = "none") +
  ggtitle("Hopelessness") + 
  geom_line_interactive(aes(tooltip = "ID", data_id = "ID", hover_css = "stroke:orange"))
```

```{r echo=FALSE, results='hide', warning=FALSE}
#Hope <- ggplot(EMA_DF, aes(x = ObsNum, y= Hopelessness_Raw))

#Ho_gg <- Hope + geom_line_interactive(data = EMA_DF, aes(tooltip = ID, data_id = ID))

#ggiraph(code = print(Ho_gg), hover_css = "fill:red;stroke:red;")

```


```{r, echo=FALSE, results='hide', warning=FALSE}
HopelessPlot02 <- ggplot(EMA_DFPlot, aes(x = ObsNum, y = Hopelessness_Raw)) +
  geom_line(aes(color=ID), size = 0.6) + 
  theme_light() +
  xlab("Observation Number") +
scale_color_manual(values = c("gray", "gray", "gray", "gray", "gray", "gray", "gray", "gray", "gray", "gray","gray", "gray", "gray", "gray", "gray","gray", "gray", "gray", "gray", "gray","gray", "gray", "gray", "gray", "gray","gray", "gray", "gray", "gray", "gray","gray", "gray", "gray", "gray", "gray","gray", "gray", "gray", "gray", "gray","gray", "gray", "gray")) +
  theme(axis.title.y = element_blank(), legend.position = "none") +
  ggtitle("Hopelessness")

```

```{r,echo=FALSE, results='hide', warning=FALSE}
SIPlot02 <- ggplot(EMA_DFPlot, aes(x = ObsNum, y = SI)) +
  geom_line(aes(color=ID), size = 0.6) + 
  theme_light() +
  xlab("Observation Number") +
  scale_color_manual(values = c("gray", "gray", "gray", "gray", "gray", "gray", "gray", "gray", "gray", "gray","gray", "gray", "gray", "gray", "gray","gray", "gray", "gray", "gray", "gray","gray", "gray", "gray", "gray", "gray","gray", "gray", "gray", "gray", "gray","gray", "gray", "gray", "gray", "gray","gray", "gray", "gray", "gray", "gray","gray", "gray", "gray")) +
  theme(axis.title.y = element_blank(), legend.position = "none") +
  ggtitle("Suicidal Ideation")

```

```{r,echo=FALSE, results='hide', warning=FALSE}
IHTBPlot02 <- ggplot(EMA_DFPlot, aes(x = ObsNum, y = TB_Raw)) +
  geom_line(aes(color=ID), size = 0.6) + 
  theme_light() +
  scale_color_manual(values = c("gray", "gray", "gray", "gray", "gray", "gray", "gray", "gray", "gray", "gray","gray", "gray", "gray", "gray", "gray","gray", "gray", "gray", "gray", "gray","gray", "gray", "gray", "gray", "gray","gray", "gray", "gray", "gray", "gray","gray", "gray", "gray", "gray", "gray","gray", "gray", "gray", "gray", "gray","gray", "gray", "gray")) +
  theme(axis.title.y = element_blank(), axis.title.x=element_blank(), legend.position = "none") +
  ggtitle("IH-TB")

```

```{r,echo=FALSE, results='hide', warning=FALSE}
IHPBPlot02 <- ggplot(EMA_DFPlot, aes(x = ObsNum, y = PB_Raw)) +
  geom_line(aes(color=ID), size = 0.6) + 
  theme_light() +
  scale_color_manual(values = c("gray", "gray", "gray", "gray", "gray", "gray", "gray", "gray", "gray", "gray","gray", "gray", "gray", "gray", "gray","gray", "gray", "gray", "gray", "gray","gray", "gray", "gray", "gray", "gray","gray", "gray", "gray", "gray", "gray","gray", "gray", "gray", "gray", "gray","gray", "gray", "gray", "gray", "gray","gray", "gray", "gray")) +
  theme(axis.title.y = element_blank(), axis.title.x=element_blank(), legend.position = "none") +
  ggtitle("IH-PB")

```

```{r,echo=FALSE, results='hide', warning=FALSE}
SI_gg <- SIPlot02 + geom_line_interactive(aes(tooltip = ID, data_id = ID), size = 0.6,color = "#b2b2b2")
#girafe(code = print(SI_gg))
```

```{r,echo=FALSE, results='hide', warning=FALSE}
x <- girafe(ggobj = SI_gg, width_svg = 8, height_svg = 6,
           options = list( opts_hover_inv(css = "opacity:0.1;"),
    opts_hover(css = "stroke-width:2;")
  ))

```

```{r,echo=FALSE, results='hide', warning=FALSE}
Ho_gg <- HopelessPlot02 + geom_line_interactive(aes(tooltip = ID, data_id = ID), size = 0.6, color = "#b2b2b2")
#girafe(code = print(Ho_gg))

x2 <- girafe(ggobj = Ho_gg, width_svg = 8, height_svg = 6,
           options = list( opts_hover_inv(css = "opacity:0.1;"),
    opts_hover(css = "stroke-width:2;")
  ))

x2

```

```{r,echo=FALSE, results='hide', warning=FALSE}
PB_gg <- IHPBPlot02 + geom_line_interactive(aes(tooltip = ID, data_id = ID), size = 0.6, color = "#b2b2b2")
#girafe(code = print(Ho_gg))

x3 <- girafe(ggobj = PB_gg, width_svg = 8, height_svg = 6,
           options = list( opts_hover_inv(css = "opacity:0.1;"),
    opts_hover(css = "stroke-width:2;")
  ))

```

```{r,echo=FALSE, results='hide', warning=FALSE}
TB_gg <- IHTBPlot02 + geom_line_interactive(aes(tooltip = ID, data_id = ID), size = 0.6, color = "#b2b2b2")
#girafe(code = print(Ho_gg))

#x4 <- girafe(ggobj = TB_gg, width_svg = 8, height_svg = 6,
#           options = list( opts_hover_inv(css = "opacity:0.1;"),
#    opts_hover(css = "stroke-width:2;")
#  ))

```

```{r,echo=FALSE, results='hide',warning=FALSE}

title_gg <- ggplot() + labs(subtitle = "Interactive Graph- Hover over lines to select participant", fontface = "italic")
title_theme <- ggdraw() +
  draw_label("Interactive Graph- Hover over line to select participant")
```

```{r, echo = FALSE, warning=FALSE}
gg_combined <- girafe(ggobj = plot_grid(PB_gg, TB_gg, Ho_gg, SI_gg, title_gg, ncol =2, rel_heights = c(2.3, 2.4, .15)),
                      width_svg = 17, height_svg = 12,
        options = list( opts_hover_inv(css = "opacity:0.02;"), opts_tooltip(use_fill = TRUE), opts_hover(css = "stroke:indigo;stroke-width:2;")), opts_sizing(rescale = TRUE, width = .7)) 

gg_combined 
```